config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :tops
  #root 'messages#index'
  resources :ti_tles
  resources :messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/ti_tle.rb
class TiTle < ApplicationRecord
end

app/models/top.rb
class Top < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:title)
    end
end

app/controllers/ti_tles_controller.rb
class TiTlesController < ApplicationController
  before_action :set_ti_tle, only: [:show, :edit, :update, :destroy]

  # GET /ti_tles
  # GET /ti_tles.json
  def index
    @ti_tles = TiTle.all
  end

  # GET /ti_tles/1
  # GET /ti_tles/1.json
  def show
  end

  # GET /ti_tles/new
  def new
    @ti_tle = TiTle.new
  end

  # GET /ti_tles/1/edit
  def edit
  end

  # POST /ti_tles
  # POST /ti_tles.json
  def create
    @ti_tle = TiTle.new(ti_tle_params)

    respond_to do |format|
      if @ti_tle.save
        format.html { redirect_to @ti_tle, notice: 'Ti tle was successfully created.' }
        format.json { render :show, status: :created, location: @ti_tle }
      else
        format.html { render :new }
        format.json { render json: @ti_tle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ti_tles/1
  # PATCH/PUT /ti_tles/1.json
  def update
    respond_to do |format|
      if @ti_tle.update(ti_tle_params)
        format.html { redirect_to @ti_tle, notice: 'Ti tle was successfully updated.' }
        format.json { render :show, status: :ok, location: @ti_tle }
      else
        format.html { render :edit }
        format.json { render json: @ti_tle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ti_tles/1
  # DELETE /ti_tles/1.json
  def destroy
    @ti_tle.destroy
    respond_to do |format|
      format.html { redirect_to ti_tles_url, notice: 'Ti tle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ti_tle
      @ti_tle = TiTle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ti_tle_params
      params.require(:ti_tle).permit(:title, :message)
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  before_action :set_top, only: [:show, :edit, :update, :destroy]

  # GET /tops
  # GET /tops.json
  def index
    @tops = Top.all
  end

  # GET /tops/1
  # GET /tops/1.json
  def show
  end

  # GET /tops/new
  def new
    @top = Top.new
  end

  # GET /tops/1/edit
  def edit
  end

  # POST /tops
  # POST /tops.json
  def create
    @top = Top.new(top_params)

    respond_to do |format|
      if @top.save
        format.html { redirect_to @top, notice: 'Top was successfully created.' }
        format.json { render :show, status: :created, location: @top }
      else
        format.html { render :new }
        format.json { render json: @top.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tops/1
  # PATCH/PUT /tops/1.json
  def update
    respond_to do |format|
      if @top.update(top_params)
        format.html { redirect_to @top, notice: 'Top was successfully updated.' }
        format.json { render :show, status: :ok, location: @top }
      else
        format.html { render :edit }
        format.json { render json: @top.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tops/1
  # DELETE /tops/1.json
  def destroy
    @top.destroy
    respond_to do |format|
      format.html { redirect_to tops_url, notice: 'Top was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_top
      @top = Top.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def top_params
      params.require(:top).permit(:title, :mess)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/ti_tles_helper.rb
module TiTlesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(message) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.title %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @message.title %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/ti_tles/_form.html.erb
<%= form_for(ti_tle) do |f| %>
  <% if ti_tle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ti_tle.errors.count, "error") %> prohibited this ti_tle from being saved:</h2>

      <ul>
      <% ti_tle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_field :message %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ti_tles/edit.html.erb
<h1>Editing Ti Tle</h1>

<%= render 'form', ti_tle: @ti_tle %>

<%= link_to 'Show', @ti_tle %> |
<%= link_to 'Back', ti_tles_path %>

app/views/ti_tles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ti Tles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ti_tles.each do |ti_tle| %>
      <tr>
        <td><%= ti_tle.title %></td>
        <td><%= ti_tle.message %></td>
        <td><%= link_to 'Show', ti_tle %></td>
        <td><%= link_to 'Edit', edit_ti_tle_path(ti_tle) %></td>
        <td><%= link_to 'Destroy', ti_tle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ti Tle', new_ti_tle_path %>

app/views/ti_tles/new.html.erb
<h1>New Ti Tle</h1>

<%= render 'form', ti_tle: @ti_tle %>

<%= link_to 'Back', ti_tles_path %>

app/views/ti_tles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ti_tle.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @ti_tle.message %>
</p>

<%= link_to 'Edit', edit_ti_tle_path(@ti_tle) %> |
<%= link_to 'Back', ti_tles_path %>

app/views/tops/_form.html.erb
<%= form_for(top) do |f| %>
  <% if top.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(top.errors.count, "error") %> prohibited this top from being saved:</h2>

      <ul>
      <% top.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :mess %>
    <%= f.text_field :mess %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tops/edit.html.erb
<h1>Editing Top</h1>

<%= render 'form', top: @top %>

<%= link_to 'Show', @top %> |
<%= link_to 'Back', tops_path %>

app/views/tops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tops</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Mess</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tops.each do |top| %>
      <tr>
        <td><%= top.title %></td>
        <td><%= top.mess %></td>
        <td><%= link_to 'Show', top %></td>
        <td><%= link_to 'Edit', edit_top_path(top) %></td>
        <td><%= link_to 'Destroy', top, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Top', new_top_path %>

app/views/tops/new.html.erb
<h1>New Top</h1>

<%= render 'form', top: @top %>

<%= link_to 'Back', tops_path %>

app/views/tops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @top.title %>
</p>

<p>
  <strong>Mess:</strong>
  <%= @top.mess %>
</p>

<%= link_to 'Edit', edit_top_path(@top) %> |
<%= link_to 'Back', tops_path %>